version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/user_image_train
    ports:
      - 9100:9100
    image: app:user_image_train
    container_name: user_image_container
    command: python manage.py runserver 0.0.0.0:9100
    networks:
      - mysql-network

networks:
  mysql-network:
    external:
      name: mysql-network
